### ISSUE TITLE
Create issues for upstream CMS project

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#169]
Create issues in the Netlify CMS project for problems that we found in usability testing.
- [x] Workflow status changes should update the PR
  - Add label for "draft", "in review", "ready" (issue raised https://github.com/netlify/netlify-cms/issues/1617)
  - OR, only create the PR when draft moves to "in review"
- [x] Link from CMS to PR, and from PR to CMS - raised https://github.com/netlify/netlify-cms/issues/1929
- [x] Improve status UI - raised https://github.com/netlify/netlify-cms/issues/1929
  - Don't show the publish button unless the post is in ready status
  - Hide the publish button entirely if you don't have access
  - Ask @acammies  to sketch up a UI mock
- [x] When using editorial workflow, images should be uploaded to the branch, not directly to master. (See #188)
  - Commented on existing issue: https://github.com/netlify/netlify-cms/issues/1344
- [ ] Allow users of github workflow to create forks rather than branches
  - This would allow us to take contributions from folks who aren't members of the repo without dealing with the limitations of the "Git Gateway + Bot account" setup
  - On second thought, let's not request that for now. That seems like a complicated feature to implement, especially considering that Netlify now supports Bitbucket, GitLab, etc.
- [x] When an existing `cms/<NAME>` branch exists, the CMS fails to save new drafts. It should either use the existing branch or create a new one. See #329. - https://github.com/netlify/netlify-cms/issues/1493

**Comment by tech4him1** [comment]
@rdebeasi Maintainer for Netlify CMS here -- really appreciate you guys making the effort to send these back upstream!

**Comment by rdebeasi** [comment]
We've found or created issues for everything except the "fork rather than branch" feature. I imagine that would be really difficult in a way that works across Git providers, and fixes for other issues would make the "gateway + bot" setup work a lot better.
