### ISSUE TITLE
Improve Editorial Workflow

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#557]
Let's work with the upstream Netlify CMS community to improve editorial workflow.

### Problem

Authors draft content in Netlify CMS, but the rest of the review and publishing process happens in GitHub issues. Jumping between the two systems confuses most new contributors. Documentation and configuration tweaks have been a band-aid over the problem but haven't really solved it.

Additionally, access to the CMS is currently all-or-nothing, so contributors can accidentally bypass the review process and promote their content to staging. A moderator or maintainer still needs to promote the content from staging to master, and we could probably hide the publish button - but again, both of these are short-term solutions.

### Solution
- [ ] Use GitHub teams + Netlify CMS config to allow contributors to draft content but not publish it. https://github.com/netlify/netlify-cms/issues/2
- [ ] Allow contributors to fork the repo rather than creating a branch in the repo. (I don't have an issue for this feature, but the Netlify CMS folks say it's in the works.)
- [ ] Allow users to upload media without having write access to the "main" branch. https://github.com/netlify/netlify-cms/issues/1344
- [ ] Show PR comments and status in Netlify CMS. https://github.com/netlify/netlify-cms/issues/1929#issuecomment-444603385, https://github.com/netlify/netlify-cms/issues/1617, https://github.com/netlify/netlify-cms/issues/53

**Comment by lallmon** [comment]
Closing this as we have a whole Epic around Editorial Workflow!
